version: '3.8'

services:
  launcher:
    build:
      context: .
      network: host
    environment:
      - PORT=1337
      - HTTP_PORT=31337
      - ETH_RPC_URL=https://eth.llamarpc.com
      - FLAG=SEKAI{super-duper-memory-master-:3}
      - PUBLIC_IP=zoo.chals.sekai.team
      - SHARED_SECRET=super-duper-secret-k3y
    ports:
      - "1337:1337"
      - "31337:31337"
